# Generated by Django 4.2.13 on 2026-06-03 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cooperatives', '0001_initial'),
        ('transport', '0001_initial'),
        ('distribution', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('dispatch_weight_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quality_grade_at_dispatch', models.CharField(choices=[('A', 'Grade A — Premium'), ('B', 'Grade B — Standard'), ('C', 'Grade C — Below Standard')], max_length=1)),
                ('dispatch_timestamp', models.DateTimeField()),
                ('dispatch_gps_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('dispatch_gps_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('weight_at_distributor_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quality_at_distributor', models.CharField(blank=True, choices=[('A', 'Grade A — Premium'), ('B', 'Grade B — Standard'), ('C', 'Grade C — Below Standard')], max_length=1)),
                ('distributor_receipt_timestamp', models.DateTimeField(blank=True, null=True)),
                ('current_status', models.CharField(choices=[('AT_COOPERATIVE', 'At Cooperative — Awaiting Dispatch'), ('IN_TRANSIT_LEG1', 'In Transit — Leg 1 (Cooperative → Distributor)'), ('AT_DISTRIBUTOR', 'At Distributor'), ('IN_TRANSIT_LEG2', 'In Transit — Leg 2 (Distributor → Market Agent)'), ('AT_MARKET', 'At Market Agent Stall'), ('COMPLETED', 'Completed — Waste Report Submitted')], default='AT_COOPERATIVE', max_length=20)),
                ('transit_loss_leg1_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('transit_loss_leg1_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('self_transport_loss_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('self_transport_loss_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('market_spoilage_loss_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('market_spoilage_loss_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_loss_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_loss_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='cooperatives.cooperative')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='cooperatives.crop')),
                ('dispatched_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatched_batches', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch', to='distribution.order')),
                ('received_by_distributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_batches', to='distribution.distributor')),
                ('stock_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='cooperatives.cooperativestock')),
                ('supply_agreement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='distribution.supplyagreement')),
                ('transport_request_leg1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_leg1', to='transport.transportrequest')),
                ('transport_request_leg2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_leg2', to='transport.transportrequest')),
            ],
            options={
                'ordering': ['-dispatch_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='QRCodeScanEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_point', models.CharField(choices=[('PICKUP_CONFIRMATION', 'Transporter Pickup Confirmed'), ('DISTRIBUTOR_RECEIPT', 'Distributor Receipt Confirmed'), ('AGENT_COLLECTION', 'Market Agent Collection Confirmed')], max_length=30)),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qr_scans', to='traceability.batch')),
                ('scanned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qr_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scanned_at'],
                'default_permissions': ('add', 'view'),
            },
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['batch_id'], name='traceabilit_batch_i_2bdbe6_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['current_status'], name='traceabilit_current_a60564_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['cooperative', 'dispatch_timestamp'], name='traceabilit_coopera_86fc8c_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['received_by_distributor', 'distributor_receipt_timestamp'], name='traceabilit_receive_d84f4f_idx'),
        ),
    ]
