# Generated by Django 4.2.13 on 2026-07-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traceability', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='mismatch_description',
            field=models.CharField(blank=True, help_text="What was actually received, e.g. 'Potatoes instead of Tomatoes'", max_length=200),
        ),
        migrations.AddField(
            model_name='batch',
            name='mismatch_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='mismatch_reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='batch',
            name='mismatch_reported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
