# Generated by Django 4.2.13 on 2026-06-03 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cooperatives', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_quantity_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('collection_deadline', models.DateTimeField()),
                ('pickup_location', models.CharField(max_length=300)),
                ('pickup_gps_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('pickup_gps_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('warehouse_location', models.CharField(max_length=300)),
                ('warehouse_gps_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('warehouse_gps_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('district', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DistributorMarketAgentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProduceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quality_grade_required', models.CharField(choices=[('A', 'Grade A — Premium'), ('B', 'Grade B — Standard'), ('C', 'Grade C — Any Available')], max_length=1)),
                ('required_delivery_date', models.DateField()),
                ('additional_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Cooperative Response'), ('ACCEPTED', 'Accepted'), ('NEGOTIATING', 'Under Negotiation'), ('DECLINED', 'Declined'), ('COMPLETED', 'Completed (batch delivered)'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('cooperative_response_notes', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produce_requests_received', to='cooperatives.cooperative')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cooperatives.crop')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produce_requests', to='distribution.distributor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplyAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreed_quantity_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('agreed_quality_grade', models.CharField(max_length=1)),
                ('agreed_delivery_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('produce_request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='supply_agreement', to='distribution.producerequest')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_requested_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preferred_collection_date', models.DateField(blank=True, null=True)),
                ('confirmed_quantity_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('adjustment_reason', models.TextField(blank=True)),
                ('delivery_method', models.CharField(blank=True, choices=[('SELF_COLLECTION', 'Agent Self-Collection'), ('TRANSPORTER_DELIVERY', 'Distributor-Arranged Transporter Delivery')], max_length=30, null=True)),
                ('status', models.CharField(choices=[('PENDING_CONFIRMATION', 'Pending Distributor Confirmation'), ('CONFIRMED', 'Confirmed'), ('ADJUSTED', 'Quantity Adjusted'), ('DECLINED', 'Declined'), ('COLLECTED', 'Produce Collected'), ('WASTE_REPORTED', 'Waste Report Submitted'), ('COMPLETED', 'Completed')], default='PENDING_CONFIRMATION', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection_notice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='distribution.collectionnotice')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='distribution.distributor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
