# Generated by Django 4.2.13 on 2026-06-03 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market_agents', '0001_initial'),
        ('transport', '0001_initial'),
        ('distribution', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cooperatives', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='market_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='market_agents.marketagent'),
        ),
        migrations.AddField(
            model_name='order',
            name='transporter',
            field=models.ForeignKey(blank=True, help_text='Only set when delivery_method is TRANSPORTER_DELIVERY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leg2_orders', to='transport.transporter'),
        ),
        migrations.AddField(
            model_name='distributormarketagentlink',
            name='distributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_agent_links', to='distribution.distributor'),
        ),
        migrations.AddField(
            model_name='distributormarketagentlink',
            name='market_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributor_links', to='market_agents.marketagent'),
        ),
        migrations.AddField(
            model_name='distributor',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'DISTRIBUTOR'}, on_delete=django.db.models.deletion.PROTECT, related_name='distributor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collectionnotice',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cooperatives.crop'),
        ),
        migrations.AddField(
            model_name='collectionnotice',
            name='distributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_notices', to='distribution.distributor'),
        ),
        migrations.AlterUniqueTogether(
            name='distributormarketagentlink',
            unique_together={('distributor', 'market_agent')},
        ),
    ]
