# Generated by Django 4.2.13 on 2026-06-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionnotice',
            name='price_per_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='RWF per kg — lets market agents compare distributors before connecting.', max_digits=10, null=True),
        ),
    ]
