# Generated by Django 4.2.13 on 2026-06-22 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0003_collectionnotice_price_per_kg'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributorWasteReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_period_start', models.DateField()),
                ('reporting_period_end', models.DateField()),
                ('quantity_moved_kg', models.DecimalField(decimal_places=2, help_text='Quantity sold on / collected by market agents during this period', max_digits=10)),
                ('quantity_discarded_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discard_reason', models.CharField(choices=[('SPOILAGE', 'Spoilage — natural deterioration'), ('NO_DEMAND', 'No demand — not collected before spoilage'), ('DAMAGE', 'Physical/handling damage in warehouse'), ('OTHER', 'Other — see notes')], max_length=20)),
                ('discard_notes', models.TextField(blank=True)),
                ('warehouse_spoilage_loss_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waste_reports', to='distribution.distributor')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
