# Generated by Django 4.2.13 on 2026-07-12 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0006_cooperativewastereport_crop'),
        ('distribution', '0004_distributorwastereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributorwastereport',
            name='crop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='distributor_waste_reports', to='cooperatives.crop'),
        ),
    ]
