# Generated by Django 4.2.13 on 2026-07-12 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0005_distributorwastereport_crop'),
    ]

    operations = [
        migrations.AddField(
            model_name='producerequest',
            name='delivery_method',
            field=models.CharField(choices=[('SELF_COLLECTION', 'Distributor Self-Collection'), ('TRANSPORTER_DELIVERY', 'Cooperative-Arranged Transporter Delivery')], default='TRANSPORTER_DELIVERY', max_length=25),
        ),
    ]
