# Generated by Django 4.2.13 on 2026-06-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessrequest',
            name='role_requested',
            field=models.CharField(choices=[('ADMIN', 'System Administrator'), ('COOPERATIVE_MANAGER', 'Cooperative Manager'), ('TRANSPORTER', 'Transporter'), ('DISTRIBUTOR', 'Distributor'), ('MARKET_AGENT', 'Market Agent'), ('MINAGRI_OFFICER', 'MINAGRI Officer'), ('WAREHOUSE_MANAGER', 'Warehouse Manager')], max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'System Administrator'), ('COOPERATIVE_MANAGER', 'Cooperative Manager'), ('TRANSPORTER', 'Transporter'), ('DISTRIBUTOR', 'Distributor'), ('MARKET_AGENT', 'Market Agent'), ('MINAGRI_OFFICER', 'MINAGRI Officer'), ('WAREHOUSE_MANAGER', 'Warehouse Manager')], max_length=30),
        ),
    ]
