# Generated by Django 4.2.13 on 2026-06-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_accessrequest_role_requested_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessrequest',
            name='role_requested',
            field=models.CharField(choices=[('ADMIN', 'System Administrator'), ('COOPERATIVE_MANAGER', 'Cooperative Manager'), ('TRANSPORT_COMPANY', 'Transport Company'), ('TRANSPORTER', 'Transporter'), ('DISTRIBUTOR', 'Distributor'), ('MARKET_AGENT', 'Market Agent'), ('MINAGRI_OFFICER', 'MINAGRI Officer'), ('WAREHOUSE_MANAGER', 'Warehouse Manager')], max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'System Administrator'), ('COOPERATIVE_MANAGER', 'Cooperative Manager'), ('TRANSPORT_COMPANY', 'Transport Company'), ('TRANSPORTER', 'Transporter'), ('DISTRIBUTOR', 'Distributor'), ('MARKET_AGENT', 'Market Agent'), ('MINAGRI_OFFICER', 'MINAGRI Officer'), ('WAREHOUSE_MANAGER', 'Warehouse Manager')], max_length=30),
        ),
    ]
