# Generated by Django 4.2.13 on 2026-07-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_accessrequest_role_requested_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('FAILED_LOGIN', 'Failed Login Attempt'), ('ACCOUNT_CREATED', 'Account Created'), ('ACCOUNT_SUSPENDED', 'Account Suspended'), ('ACCOUNT_ACTIVATED', 'Account Activated'), ('PASSWORD_CHANGED', 'Password Changed'), ('OTP_SENT', 'OTP Sent'), ('OTP_VERIFIED', 'OTP Verified'), ('MFA_ENABLED', 'Two-Factor Authentication Enabled'), ('MFA_DISABLED', 'Two-Factor Authentication Disabled'), ('DATA_CREATED', 'Record Created'), ('DATA_UPDATED', 'Record Updated'), ('DATA_DELETED', 'Record Deleted'), ('REPORT_GENERATED', 'Report Generated'), ('REPORT_DOWNLOADED', 'Report Downloaded'), ('BATCH_DISPATCHED', 'Batch Dispatched'), ('BATCH_RECEIVED', 'Batch Received'), ('WASTE_REPORT', 'Waste Report Submitted'), ('PERMISSION_DENIED', 'Permission Denied')], max_length=30),
        ),
        migrations.AlterField(
            model_name='otprecord',
            name='purpose',
            field=models.CharField(choices=[('ACCOUNT_ACTIVATION', 'Account Activation'), ('PASSWORD_RESET', 'Password Reset'), ('MFA_LOGIN', 'MFA Login'), ('MFA_ENABLE', '2FA Setup Verification'), ('CONTACT_CHANGE', 'Contact Details Change')], max_length=30),
        ),
    ]
