"""
Reports models: Generated report files stored for download.
All reports are generated by Celery background jobs — users never wait.
"""

from django.db import models
from django.conf import settings


class Report(models.Model):
    """
    A generated supply chain report file stored for download.
    """

    class ReportType(models.TextChoices):
        NATIONAL_KPI_SUMMARY        = 'NATIONAL_KPI_SUMMARY',        'National KPI Summary'
        DISTRICT_LOSS_REPORT        = 'DISTRICT_LOSS_REPORT',        'District Loss Report'
        CROP_LOSS_REPORT            = 'CROP_LOSS_REPORT',            'Crop Loss Report'
        COLD_CHAIN_COMPLIANCE       = 'COLD_CHAIN_COMPLIANCE',       'Cold Chain Compliance Report'
        DELIVERY_METHOD_COMPARISON  = 'DELIVERY_METHOD_COMPARISON',  'Delivery Method Loss Comparison'
        STAGE_LOSS_BREAKDOWN        = 'STAGE_LOSS_BREAKDOWN',        'Stage-Specific Loss Breakdown'
        BATCH_TRACEABILITY          = 'BATCH_TRACEABILITY',          'Per-Batch Traceability Report'
        MARKET_WASTE                = 'MARKET_WASTE',                'Market-Level Waste Report'

    class Format(models.TextChoices):
        PDF   = 'PDF',   'PDF'
        EXCEL = 'EXCEL', 'Excel (.xlsx)'

    class Status(models.TextChoices):
        QUEUED     = 'QUEUED',     'Queued for Generation'
        GENERATING = 'GENERATING', 'Generating'
        READY      = 'READY',      'Ready for Download'
        FAILED     = 'FAILED',     'Generation Failed'

    report_type    = models.CharField(max_length=40, choices=ReportType.choices)
    title          = models.CharField(max_length=300)
    format         = models.CharField(max_length=10, choices=Format.choices, default=Format.PDF)
    status         = models.CharField(max_length=15, choices=Status.choices, default=Status.QUEUED)

    # Period covered
    period_start = models.DateField()
    period_end   = models.DateField()

    # Scope filters (optional — for district-specific or agent-specific reports)
    filter_district     = models.CharField(max_length=100, blank=True)
    filter_distributor  = models.ForeignKey('distribution.Distributor', on_delete=models.SET_NULL,
                                             null=True, blank=True, related_name='reports')
    filter_market_agent = models.ForeignKey('market_agents.MarketAgent', on_delete=models.SET_NULL,
                                             null=True, blank=True, related_name='reports')
    filter_batch        = models.ForeignKey('traceability.Batch', on_delete=models.SET_NULL,
                                             null=True, blank=True, related_name='reports')

    # Generated by
    generated_by_job  = models.BooleanField(default=False)  # True for scheduled Celery jobs
    generated_by_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL,
                                           null=True, blank=True, related_name='generated_reports')

    # File
    file_path    = models.FileField(upload_to='reports/%Y/%m/', blank=True)
    file_size_kb = models.IntegerField(null=True, blank=True)

    # Data confidence
    data_completeness_pct = models.IntegerField(null=True, blank=True,
        help_text="% of expected records received for this period")

    error_message = models.TextField(blank=True)
    created_at    = models.DateTimeField(auto_now_add=True)
    completed_at  = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.report_type} — {self.period_end} — {self.status}"
