# Generated by Django 4.2.13 on 2026-06-03 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cooperatives', '0001_initial'),
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleIoTReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature_celsius', models.FloatField()),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('is_breach', models.BooleanField(default=False)),
                ('alert_sent', models.BooleanField(default=False)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iot_readings', to='transport.trip')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['trip', 'timestamp'], name='iot_vehicle_trip_id_024f7a_idx')],
            },
        ),
        migrations.CreateModel(
            name='IoTReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature_celsius', models.FloatField()),
                ('humidity_percent', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('is_temperature_breach', models.BooleanField(default=False)),
                ('is_humidity_breach', models.BooleanField(default=False)),
                ('alert_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iot_readings', to='cooperatives.coldstoragefacility')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['facility', 'timestamp'], name='iot_iotread_facilit_e8e8a6_idx')],
            },
        ),
    ]
