# Generated by Django 4.2.13 on 2026-06-03 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('PRODUCE_REQUEST_RECEIVED', 'New Produce Request Received'), ('TRANSPORT_ACCEPTED', 'Transport Request Accepted'), ('DELIVERY_CONFIRMED', 'Batch Delivered to Distributor'), ('STORAGE_ALERT', 'Cold Storage Temperature Alert'), ('TRANSPORT_REQUEST_RECEIVED', 'New Transport Request'), ('COLD_CHAIN_ALERT', 'Cold Chain Temperature Breach'), ('COOP_RESPONSE', 'Cooperative Responded to Request'), ('BATCH_IN_TRANSIT', 'Batch Is Now In Transit'), ('BATCH_DELIVERED', 'Batch Arrived — Confirm Receipt'), ('AGENT_COLLECTION_CONFIRMED', 'Market Agent Collected Produce'), ('COLLECTION_NOTICE_AVAILABLE', 'New Collection Notice Available'), ('ORDER_CONFIRMED', 'Order Confirmed by Distributor'), ('ORDER_DECLINED', 'Order Declined by Distributor'), ('COLLECTION_RISK_ALERT', 'High Risk Collection Advisory'), ('DISTRICT_THRESHOLD_BREACH', 'District Loss Threshold Exceeded'), ('SEASONAL_LOSS_PREDICTION', 'Seasonal High-Loss Prediction'), ('NEW_REPORT_AVAILABLE', 'New Report Available for Download'), ('SYSTEM_ANNOUNCEMENT', 'System Announcement')], max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('related_object_type', models.CharField(blank=True, max_length=50)),
                ('related_object_id', models.CharField(blank=True, max_length=100)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', 'created_at'], name='notificatio_recipie_86ea8b_idx')],
            },
        ),
    ]
