# Generated by Django 4.2.13 on 2026-06-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('PRODUCE_REQUEST_RECEIVED', 'New Produce Request Received'), ('TRANSPORT_ACCEPTED', 'Transport Request Accepted'), ('DELIVERY_CONFIRMED', 'Batch Delivered to Distributor'), ('STORAGE_ALERT', 'Cold Storage Temperature Alert'), ('TRANSPORT_REQUEST_RECEIVED', 'New Transport Request'), ('COLD_CHAIN_ALERT', 'Cold Chain Temperature Breach'), ('INCIDENT_REPORTED', 'Transporter Reported an Incident'), ('COOP_RESPONSE', 'Cooperative Responded to Request'), ('BATCH_IN_TRANSIT', 'Batch Is Now In Transit'), ('BATCH_DELIVERED', 'Batch Arrived — Confirm Receipt'), ('AGENT_COLLECTION_CONFIRMED', 'Market Agent Collected Produce'), ('COLLECTION_NOTICE_AVAILABLE', 'New Collection Notice Available'), ('ORDER_CONFIRMED', 'Order Confirmed by Distributor'), ('ORDER_DECLINED', 'Order Declined by Distributor'), ('COLLECTION_RISK_ALERT', 'High Risk Collection Advisory'), ('DISTRICT_THRESHOLD_BREACH', 'District Loss Threshold Exceeded'), ('SEASONAL_LOSS_PREDICTION', 'Seasonal High-Loss Prediction'), ('NEW_REPORT_AVAILABLE', 'New Report Available for Download'), ('SYSTEM_ANNOUNCEMENT', 'System Announcement')], max_length=40),
        ),
    ]
