# Generated by Django 4.2.13 on 2026-07-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('PRODUCE_REQUEST_RECEIVED', 'New Produce Request Received'), ('TRANSPORT_ACCEPTED', 'Transport Request Accepted'), ('DELIVERY_CONFIRMED', 'Batch Delivered to Distributor'), ('STORAGE_ALERT', 'Cold Storage Temperature Alert'), ('TRANSPORT_REQUEST_RECEIVED', 'New Transport Request'), ('COLD_CHAIN_ALERT', 'Cold Chain Temperature Breach'), ('INCIDENT_REPORTED', 'Transporter Reported an Incident'), ('TRIP_DELAY_ALERT', 'Possible Delay — No Recent GPS Update'), ('WAREHOUSE_RENTAL_REQUESTED', 'New Warehouse Rental Request'), ('WAREHOUSE_RENTAL_RESPONSE', 'Warehouse Rental Request Update'), ('STOCK_AVAILABLE', 'New Stock Available from Cooperative'), ('COOP_RESPONSE', 'Cooperative Responded to Request'), ('BATCH_IN_TRANSIT', 'Batch Is Now In Transit'), ('BATCH_DELIVERED', 'Batch Arrived — Confirm Receipt'), ('AGENT_COLLECTION_CONFIRMED', 'Market Agent Collected Produce'), ('COLLECTION_NOTICE_AVAILABLE', 'New Collection Notice Available'), ('ORDER_CONFIRMED', 'Order Confirmed by Distributor'), ('ORDER_DECLINED', 'Order Declined by Distributor'), ('COLLECTION_RISK_ALERT', 'High Risk Collection Advisory'), ('DISTRICT_THRESHOLD_BREACH', 'District Loss Threshold Exceeded'), ('SEASONAL_LOSS_PREDICTION', 'Seasonal High-Loss Prediction'), ('NEW_REPORT_AVAILABLE', 'New Report Available for Download'), ('HIGH_SPOILAGE_ALERT', 'High Spoilage Rate Reported'), ('SYSTEM_ANNOUNCEMENT', 'System Announcement')], max_length=40),
        ),
    ]
