# Generated by Django 4.2.13 on 2026-06-03 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('distribution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stall_number', models.CharField(max_length=50)),
                ('market_name', models.CharField(max_length=200)),
                ('market_district', models.CharField(max_length=100)),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'MARKET_AGENT'}, on_delete=django.db.models.deletion.PROTECT, related_name='market_agent_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WasteReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_period_start', models.DateField()),
                ('reporting_period_end', models.DateField()),
                ('quantity_sold_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_discarded_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discard_reason', models.CharField(choices=[('SPOILAGE', 'Spoilage — natural deterioration'), ('NO_DEMAND', 'No demand — produce not sold before spoilage'), ('DAMAGE', 'Physical damage at stall'), ('OTHER', 'Other — see notes')], max_length=20)),
                ('discard_notes', models.TextField(blank=True)),
                ('market_spoilage_loss_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('idempotency_key', models.UUIDField(help_text='UUID from device — prevents duplicate offline submissions', unique=True)),
                ('market_agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waste_reports', to='market_agents.marketagent')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='waste_reports', to='distribution.order')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='CollectionConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_collected_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('collected_at', models.DateTimeField()),
                ('step1_idempotency_key', models.UUIDField(help_text='UUID from device — prevents duplicate offline submissions', unique=True)),
                ('quantity_arrived_at_stall_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('condition_code', models.CharField(blank=True, choices=[('HEAT_DAMAGE', 'Heat damage — degraded due to heat exposure during trip'), ('PHYSICAL_DAMAGE', 'Physical damage — bruising, crushing, or packaging failure'), ('PRE_EXISTING_SPOILAGE', 'Pre-existing spoilage — already degraded at distributor'), ('DELAY', 'Delay — collection trip exceeded safe window for this crop'), ('OTHER', 'Other — see notes')], max_length=30, null=True)),
                ('condition_notes', models.TextField(blank=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('step2_idempotency_key', models.UUIDField(blank=True, null=True, unique=True)),
                ('self_transport_loss_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('self_transport_loss_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('market_agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_confirmations', to='market_agents.marketagent')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_confirmations', to='distribution.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
