# Generated by Django 4.2.13 on 2026-06-03 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_agents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketagent',
            options={'ordering': ['market_name', 'stall_number']},
        ),
    ]
