# Generated by Django 4.2.13 on 2026-07-12 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0005_distributorwastereport_crop'),
        ('cooperatives', '0006_cooperativewastereport_crop'),
        ('market_agents', '0003_make_order_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastereport',
            name='crop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='market_agent_waste_reports', to='cooperatives.crop'),
        ),
    ]
