# Generated by Django 4.2.13 on 2026-06-03 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cooperatives', '0001_initial'),
        ('distribution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, help_text='Optional — for company registrations', max_length=200)),
                ('operating_districts', models.JSONField(default=list, help_text='List of districts this transporter covers')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'TRANSPORTER'}, on_delete=django.db.models.deletion.PROTECT, related_name='transporter_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leg_number', models.IntegerField(choices=[(1, 'Leg 1 — Cooperative to Distributor'), (2, 'Leg 2 — Distributor to Market Agent')])),
                ('pickup_location', models.CharField(max_length=300)),
                ('pickup_gps_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('pickup_gps_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('destination', models.CharField(max_length=300)),
                ('destination_gps_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('destination_gps_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('cargo_description', models.CharField(max_length=200)),
                ('estimated_cargo_weight_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('requires_refrigeration', models.BooleanField(default=False)),
                ('required_pickup_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Transporter Response'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('decline_reason', models.TextField(blank=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by_cooperative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_requests_sent', to='cooperatives.cooperative')),
                ('requested_by_distributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_requests_sent', to='distribution.distributor')),
                ('transporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transport_requests', to='transport.transporter')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('REFRIGERATED', 'Refrigerated Truck'), ('STANDARD_TRUCK', 'Standard Truck'), ('PICKUP', 'Pickup Truck'), ('MOTORCYCLE', 'Motorcycle'), ('MINIBUS', 'Minibus')], max_length=20)),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('capacity_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('operating_districts', models.JSONField(default=list)),
                ('has_iot_temperature', models.BooleanField(default=False)),
                ('iot_device_id', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='transport.transporter')),
            ],
            options={
                'ordering': ['plate_number'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_pickup_datetime', models.DateTimeField(blank=True, null=True)),
                ('actual_delivery_datetime', models.DateTimeField(blank=True, null=True)),
                ('pickup_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transport_request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='trip', to='transport.transportrequest')),
            ],
        ),
        migrations.AddField(
            model_name='transportrequest',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_requests', to='transport.vehicle'),
        ),
        migrations.CreateModel(
            name='GPSTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('speed_kmh', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_tracks', to='transport.trip')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['trip', 'timestamp'], name='transport_g_trip_id_5ba8ca_idx')],
            },
        ),
    ]
