# Generated by Django 4.2.13 on 2026-06-19 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_transporter_registered_by_cooperative'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('FLAT_TIRE', 'Flat Tire'), ('ACCIDENT', 'Accident'), ('BREAKDOWN', 'Vehicle Breakdown'), ('ROAD_CLOSURE', 'Road Closure / Detour'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('gps_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_reports', to='transport.trip')),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
    ]
