# Generated by Django 4.2.13 on 2026-06-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_incidentreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='delay_alert_sent',
            field=models.BooleanField(default=False, help_text="Set once a 'no recent GPS update' alert has fired for this trip."),
        ),
    ]
