# Generated by Django 4.2.13 on 2026-06-22 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_trip_delay_alert_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporter',
            name='parent_company',
            field=models.ForeignKey(blank=True, help_text='Set when this Transporter is a driver registered by a Transport Company account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='transport.transporter'),
        ),
    ]
