# Generated by Django 4.2.13 on 2026-06-22 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_transporter_parent_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportrequest',
            name='run_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Shared by all stops in the same multi-stop run.', null=True),
        ),
        migrations.AddField(
            model_name='transportrequest',
            name='stop_sequence',
            field=models.PositiveIntegerField(blank=True, help_text='Order of this stop within its run (1 = first).', null=True),
        ),
    ]
