# Generated by Django 4.2.13 on 2026-06-22 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transport', '0006_transportrequest_run_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transporter',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role__in': ['TRANSPORTER', 'TRANSPORT_COMPANY']}, on_delete=django.db.models.deletion.PROTECT, related_name='transporter_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
