# Generated by Django 4.2.13 on 2026-06-22 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0004_distributorwastereport'),
        ('transport', '0007_alter_transporter_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporter',
            name='registered_by_distributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_transporters', to='distribution.distributor'),
        ),
    ]
