# Generated by Django 4.2.13 on 2026-06-22 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0008_transporter_registered_by_distributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporter',
            name='description',
            field=models.TextField(blank=True, help_text='Company profile blurb — who we are, what we offer'),
        ),
    ]
