# Generated by Django 4.2.13 on 2026-06-22 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0009_transporter_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporter',
            name='base_location',
            field=models.CharField(blank=True, help_text="Office/depot address — e.g. 'Kacyiru, Kigali'", max_length=300),
        ),
    ]
