# Generated by Django 4.2.13 on 2026-06-23 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0004_distributorwastereport'),
        ('cooperatives', '0002_alter_coldstoragefacility_options_and_more'),
        ('transport', '0010_transporter_base_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransporterRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='1-5 stars')),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rated_by_cooperative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cooperatives.cooperative')),
                ('rated_by_distributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='distribution.distributor')),
                ('transport_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='transport.transportrequest')),
                ('transporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='transport.transporter')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
