# Generated by Django 4.2.13 on 2026-06-23 23:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0011_transporterrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpstrack',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
