# Generated by Django 4.2.13 on 2026-07-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0012_alter_gpstrack_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='condition_on_arrival',
            field=models.CharField(blank=True, choices=[('GOOD', 'Good — no visible damage'), ('MINOR_DAMAGE', 'Minor damage — some bruising/spillage'), ('MAJOR_DAMAGE', 'Major damage — significant spoilage/loss'), ('PARTIAL_QUANTITY', 'Partial — full cargo not delivered')], max_length=20),
        ),
        migrations.AddField(
            model_name='trip',
            name='delivery_gps_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='delivery_gps_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='delivery_photo',
            field=models.ImageField(blank=True, null=True, upload_to='delivery_proofs/'),
        ),
        migrations.AddField(
            model_name='trip',
            name='recipient_name',
            field=models.CharField(blank=True, help_text='Who signed for/accepted the delivery at the destination', max_length=150),
        ),
    ]
