import { useState } from 'react'
import { FileText, Download, Globe, MapPin, Leaf, Activity, Loader, BarChart3 } from 'lucide-react'
import toast from 'react-hot-toast'
import { analyticsApi, triggerDownload } from '../../api/analytics.js'

const LIVE_EXPORTS = [
  {
    type: 'complete',
    name: 'Complete Activity Report',
    desc: 'Every batch nationwide — cooperative, district, transport, distributor, and market agent in a single end-to-end report.',
    filename: 'national_complete_report',
    icon: FileText,
    color: 'text-violet-600',
    bg: 'bg-violet-50',
    // A full row-per-batch dump — a chart can't summarize it meaningfully, so CSV only.
    chartable: false,
  },
  {
    type: 'national',
    name: 'National Supply Chain Report',
    desc: 'District × crop aggregation — volumes, losses, and batch counts across all of Rwanda.',
    filename: 'national_supply_chain_report',
    icon: Globe,
    color: 'text-primary-600',
    bg: 'bg-primary-50',
    // A district × crop matrix — still a table, not a single ranking a bar chart can show.
    chartable: false,
  },
  {
    type: 'districts',
    name: 'District Performance Report',
    desc: 'District-level ranking by average loss rate, total volume, and risk classification.',
    filename: 'national_districts_report',
    icon: MapPin,
    color: 'text-indigo-600',
    bg: 'bg-indigo-50',
    chartable: true,
  },
  {
    type: 'crops',
    name: 'Crop Loss Analysis Report',
    desc: 'National average loss per crop type with volume and batch count statistics.',
    filename: 'national_crops_report',
    icon: Leaf,
    color: 'text-success-600',
    bg: 'bg-success-50',
    chartable: true,
  },
  {
    type: 'transport',
    name: 'National Transport Performance',
    desc: 'Summary of all transport jobs — routes, transit times, on-time rates, and delay analysis.',
    filename: 'national_transport_report',
    icon: Activity,
    color: 'text-orange-600',
    bg: 'bg-orange-50',
    chartable: true,
  },
]

export default function NationalReports() {
  const [downloading, setDownloading] = useState(new Set())

  const handleLiveDownload = async (report, format) => {
    const key = `${report.type}:${format}`
    if (downloading.has(key)) return
    setDownloading(prev => new Set([...prev, key]))
    try {
      const res = await analyticsApi.exportReport({ report_type: report.type, file_format: format })
      triggerDownload(res, `${report.filename}.${format}`)
      toast.success(`"${report.name}" downloaded`)
    } catch {
      toast.error('Could not generate report. Try again.')
    } finally {
      setDownloading(prev => {
        const next = new Set(prev)
        next.delete(key)
        return next
      })
    }
  }

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-gray-900">Reports</h1>
        <p className="text-sm text-gray-500 mt-0.5">Download official reports generated by the ChainSight analytics system</p>
      </div>

      {/* Live CSV Exports */}
      <div className="card">
        <h2 className="font-semibold text-gray-900 mb-1">Live Data Export</h2>
        <p className="text-xs text-gray-400 mb-5">Generated instantly from the current database — always reflects the latest data</p>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          {LIVE_EXPORTS.map(report => {
            const Icon = report.icon
            return (
              <div
                key={report.type}
                className="flex flex-col gap-4 p-4 bg-gray-50 rounded-xl border border-gray-100 hover:bg-gray-100 transition-colors"
              >
                <div className="flex items-start gap-3">
                  <div className={`w-9 h-9 rounded-xl flex items-center justify-center shrink-0 ${report.bg}`}>
                    <Icon className={`w-5 h-5 ${report.color}`} />
                  </div>
                  <div className="flex-1 min-w-0">
                    <p className="text-sm font-semibold text-gray-900">{report.name}</p>
                    <p className="text-xs text-gray-500 mt-0.5 leading-relaxed">{report.desc}</p>
                  </div>
                </div>
                <div className="flex items-center justify-between pt-2 border-t border-gray-200">
                  <span className="text-xs font-medium text-gray-400 uppercase tracking-wide">
                    {report.chartable ? 'CSV or Chart PDF · Live' : 'CSV · Live'}
                  </span>
                  <div className="flex items-center gap-2">
                    {report.chartable && (
                      <button
                        onClick={() => handleLiveDownload(report, 'pdf')}
                        disabled={downloading.has(`${report.type}:pdf`)}
                        title="Download as a PDF with a summary chart"
                        className="btn-secondary flex items-center gap-2 text-sm py-2 px-3 disabled:opacity-60"
                      >
                        {downloading.has(`${report.type}:pdf`)
                          ? <Loader className="w-4 h-4 animate-spin" />
                          : <BarChart3 className="w-4 h-4" />
                        }
                        Chart PDF
                      </button>
                    )}
                    <button
                      onClick={() => handleLiveDownload(report, 'csv')}
                      disabled={downloading.has(`${report.type}:csv`)}
                      className="btn-primary flex items-center gap-2 text-sm py-2 px-4 disabled:opacity-60"
                    >
                      {downloading.has(`${report.type}:csv`)
                        ? <Loader className="w-4 h-4 animate-spin" />
                        : <Download className="w-4 h-4" />
                      }
                      {downloading.has(`${report.type}:csv`) ? 'Generating…' : 'CSV'}
                    </button>
                  </div>
                </div>
              </div>
            )
          })}
        </div>
      </div>
    </div>
  )
}
