import { TrendingUp, TrendingDown, Brain, AlertTriangle, Calendar } from 'lucide-react'
import RiskBadge from '../../components/ui/RiskBadge.jsx'

const PREDICTIONS = [
  {
    crop: 'Tomatoes',
    region: 'Northern Province',
    current_price: 850,
    predicted_price: 920,
    predicted_supply_tons: 1650,
    confidence: 82,
    risk: 'low',
    insight: 'Strong rainfall in Musanze expected to boost yields. Slight price increase driven by regional demand.',
    horizon: '30 days',
  },
  {
    crop: 'Avocados',
    region: 'Southern Province',
    current_price: 1200,
    predicted_price: 1050,
    predicted_supply_tons: 1100,
    confidence: 76,
    risk: 'medium',
    insight: 'Seasonal harvest glut likely. Price expected to soften. Distributors advised to adjust procurement volumes.',
    horizon: '30 days',
  },
  {
    crop: 'Maize',
    region: 'Eastern Province',
    current_price: 400,
    predicted_price: 450,
    predicted_supply_tons: 900,
    confidence: 70,
    risk: 'medium',
    insight: 'Dry spell forecast may reduce Eastern Province yields by 18%. Recommend strategic reserve activation.',
    horizon: '45 days',
  },
  {
    crop: 'Potatoes',
    region: 'Western Province',
    current_price: 350,
    predicted_price: 530,
    predicted_supply_tons: 280,
    confidence: 88,
    risk: 'high',
    insight: 'Critical supply shortage projected. Pest outbreak detected in 3 cooperatives. Immediate intervention recommended.',
    horizon: '20 days',
  },
]

export default function PredictionsPage() {
  return (
    <div className="space-y-6">
      <div>
        <div className="flex items-center gap-2 mb-1">
          <Brain className="w-5 h-5 text-primary-500" />
          <h1 className="text-2xl font-bold text-gray-900">AI Predictions</h1>
        </div>
        <p className="text-sm text-gray-500">ML-powered forecasts for supply, demand, and price over the next 20–45 days.</p>
      </div>

      <div className="p-4 bg-primary-50 border border-primary-200 rounded-xl text-sm text-primary-700 flex items-start gap-3">
        <Brain className="w-4 h-4 flex-shrink-0 mt-0.5" />
        <p>Predictions are generated by the ChainSight ML engine trained on 3 years of historical market, weather, and supply chain data. Confidence scores reflect model certainty at time of generation.</p>
      </div>

      <div className="space-y-4">
        {PREDICTIONS.map(p => {
          const priceChange = p.predicted_price - p.current_price
          const pricePct = ((priceChange / p.current_price) * 100).toFixed(1)
          const isUp = priceChange > 0

          return (
            <div key={`${p.crop}-${p.region}`} className={`card border-2 ${p.risk === 'high' ? 'border-danger-500' : p.risk === 'medium' ? 'border-warning-500' : 'border-success-500'}`}>
              <div className="flex items-start justify-between mb-3">
                <div>
                  <div className="flex items-center gap-2">
                    <h3 className="font-semibold text-gray-900">{p.crop}</h3>
                    <RiskBadge risk={p.risk} />
                  </div>
                  <p className="text-xs text-gray-500 mt-0.5 flex items-center gap-1">
                    <Calendar className="w-3 h-3" /> {p.region} · Horizon: {p.horizon}
                  </p>
                </div>
                <div className="text-right">
                  <p className="text-xs text-gray-400">Model confidence</p>
                  <p className={`text-lg font-bold ${p.confidence >= 80 ? 'text-success-500' : p.confidence >= 70 ? 'text-warning-500' : 'text-danger-500'}`}>{p.confidence}%</p>
                </div>
              </div>

              <div className="grid grid-cols-3 gap-3 mb-3">
                <div className="bg-gray-50 rounded-lg p-3 text-sm">
                  <p className="text-xs text-gray-500">Current price</p>
                  <p className="font-bold text-gray-900 mt-0.5">RWF {p.current_price.toLocaleString()}/kg</p>
                </div>
                <div className={`rounded-lg p-3 text-sm ${isUp ? 'bg-success-50' : 'bg-danger-50'}`}>
                  <p className={`text-xs ${isUp ? 'text-success-500' : 'text-danger-500'}`}>Predicted price</p>
                  <div className="flex items-center gap-1 mt-0.5">
                    <p className={`font-bold ${isUp ? 'text-success-500' : 'text-danger-500'}`}>RWF {p.predicted_price.toLocaleString()}/kg</p>
                    {isUp ? <TrendingUp className="w-3 h-3 text-success-500" /> : <TrendingDown className="w-3 h-3 text-danger-500" />}
                    <span className={`text-xs ${isUp ? 'text-success-500' : 'text-danger-500'}`}>{isUp ? '+' : ''}{pricePct}%</span>
                  </div>
                </div>
                <div className="bg-gray-50 rounded-lg p-3 text-sm">
                  <p className="text-xs text-gray-500">Predicted supply</p>
                  <p className="font-bold text-gray-900 mt-0.5">{p.predicted_supply_tons.toLocaleString()} tons</p>
                </div>
              </div>

              <div className={`p-3 rounded-lg text-sm ${p.risk === 'high' ? 'bg-danger-50 text-danger-500' : 'bg-gray-50 text-gray-600'}`}>
                {p.risk === 'high' && <AlertTriangle className="w-4 h-4 inline mr-1.5 mb-0.5" />}
                {p.insight}
              </div>
            </div>
          )
        })}
      </div>
    </div>
  )
}
