# Generated by Django 4.2.13 on 2026-06-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('DAILY_BRIEF', 'Daily Intelligence Brief'), ('NATIONAL_LOSS', 'National Loss Summary'), ('STAGE_BREAKDOWN', 'Stage-by-Stage Breakdown'), ('ROUTE_ALERT', 'Route Loss Alert'), ('COLD_CHAIN_ALERT', 'Cold Chain Alert'), ('DELIVERY_INSIGHT', 'Delivery Method Insight'), ('COOP_PERFORMANCE', 'Cooperative Performance'), ('AGENT_ALERT', 'Market Agent High-Loss Alert'), ('SEASONAL_OUTLOOK', 'Seasonal Outlook'), ('RECOMMENDATION', 'Actionable Recommendation')], max_length=30)),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('data_period_start', models.DateField()),
                ('data_period_end', models.DateField()),
                ('is_critical', models.BooleanField(default=False)),
                ('alert_triggered', models.BooleanField(default=False)),
                ('related_district', models.CharField(blank=True, max_length=100)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyBriefBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brief_date', models.DateField(unique=True)),
                ('summary_text', models.TextField(help_text='Headline summary shown at top of brief')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('insights', models.ManyToManyField(related_name='bundles', to='ai_insights.aiinsight')),
            ],
            options={
                'ordering': ['-brief_date'],
            },
        ),
    ]
