# Generated by Django 4.2.13 on 2026-06-03 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market_agents', '0001_initial'),
        ('ai_insights', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinsight',
            name='related_market_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_insights', to='market_agents.marketagent'),
        ),
        migrations.AddIndex(
            model_name='aiinsight',
            index=models.Index(fields=['insight_type', 'generated_at'], name='ai_insights_insight_017531_idx'),
        ),
    ]
