# Generated by Django 4.2.13 on 2026-06-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CooperativeReliabilityHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_starting', models.DateField()),
                ('reliability_score', models.DecimalField(decimal_places=2, max_digits=3)),
                ('on_time_dispatch_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quality_consistency', models.DecimalField(decimal_places=2, max_digits=5)),
                ('response_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('batches_this_week', models.IntegerField(default=0)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-week_starting'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryMethodComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_starting', models.DateField()),
                ('district', models.CharField(blank=True, max_length=100)),
                ('self_collection_orders', models.IntegerField(default=0)),
                ('self_collection_avg_loss_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('transporter_orders', models.IntegerField(default=0)),
                ('transporter_avg_loss_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('potential_saving_kg_per_week', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('recommended_method', models.CharField(blank=True, max_length=30)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-week_starting'],
            },
        ),
        migrations.CreateModel(
            name='NationalDailyKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_batches', models.IntegerField(default=0)),
                ('total_volume_dispatched_kg', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_volume_received_kg', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_loss_kg', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_loss_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('storage_loss_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transit_leg1_loss_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('self_transport_loss_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('market_spoilage_loss_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('active_cooperatives', models.IntegerField(default=0)),
                ('active_transporters', models.IntegerField(default=0)),
                ('active_distributors', models.IntegerField(default=0)),
                ('active_market_agents', models.IntegerField(default=0)),
                ('on_time_delivery_rate_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'National Daily KPI',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DistrictDailyKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('district_name', models.CharField(max_length=100)),
                ('volume_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_loss_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('loss_rate_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('top_loss_stage', models.CharField(blank=True, max_length=20)),
                ('top_loss_crop', models.CharField(blank=True, max_length=100)),
                ('batch_count', models.IntegerField(default=0)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'District Daily KPI',
                'ordering': ['-date', '-loss_rate_pct'],
                'unique_together': {('date', 'district_name')},
            },
        ),
    ]
