# Generated by Django 4.2.13 on 2026-06-03 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('market_agents', '0001_initial'),
        ('cooperatives', '0001_initial'),
        ('distribution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverymethodcomparison',
            name='distributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_comparisons', to='distribution.distributor'),
        ),
        migrations.AddField(
            model_name='deliverymethodcomparison',
            name='market_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_comparisons', to='market_agents.marketagent'),
        ),
        migrations.AddField(
            model_name='cooperativereliabilityhistory',
            name='cooperative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reliability_history', to='cooperatives.cooperative'),
        ),
        migrations.AlterUniqueTogether(
            name='cooperativereliabilityhistory',
            unique_together={('cooperative', 'week_starting')},
        ),
    ]
