# Generated by Django 4.2.13 on 2026-06-03 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cooperative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('registration_number', models.CharField(max_length=100, unique=True)),
                ('district', models.CharField(max_length=100)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('reliability_score', models.DecimalField(decimal_places=2, default=0.0, help_text='0.00–5.00 star rating. Auto-calculated weekly.', max_digits=3)),
                ('on_time_dispatch_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('quality_consistency_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('response_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_batches_dispatched', models.PositiveIntegerField(default=0)),
                ('reliability_last_updated', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('PERISHABLE', 'Perishable'), ('DRY_GOODS', 'Dry Goods'), ('ROOT_TUBERS', 'Root & Tubers'), ('FRUITS', 'Fruits')], max_length=20)),
                ('requires_cold_chain', models.BooleanField(default=False)),
                ('safe_transit_hours_amber', models.FloatField(help_text='Transit hours before Amber risk')),
                ('safe_transit_hours_red', models.FloatField(help_text='Transit hours before Red risk')),
                ('safe_temp_max_amber', models.FloatField(blank=True, help_text='Max temp (°C) before Amber', null=True)),
                ('safe_temp_max_red', models.FloatField(blank=True, help_text='Max temp (°C) before Red', null=True)),
                ('safe_storage_days_amber', models.IntegerField(default=30, help_text='Storage days before Amber risk')),
                ('safe_storage_days_red', models.IntegerField(default=60, help_text='Storage days before Red risk')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CooperativeStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quality_grade', models.CharField(choices=[('A', 'Grade A — Premium'), ('B', 'Grade B — Standard'), ('C', 'Grade C — Below Standard')], max_length=1)),
                ('harvest_date', models.DateField()),
                ('available_from', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_records', to='cooperatives.cooperative')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_records', to='cooperatives.crop')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='cooperative',
            name='crops_specialised',
            field=models.ManyToManyField(blank=True, related_name='cooperatives', to='cooperatives.crop'),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='manager',
            field=models.OneToOneField(limit_choices_to={'role': 'COOPERATIVE_MANAGER'}, on_delete=django.db.models.deletion.PROTECT, related_name='cooperative', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ColdStorageFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('capacity_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location_description', models.TextField(blank=True)),
                ('has_iot_sensor', models.BooleanField(default=False)),
                ('sensor_device_id', models.CharField(blank=True, help_text='ESP32 device identifier', max_length=100)),
                ('temp_threshold_amber_celsius', models.FloatField(default=15.0)),
                ('temp_threshold_red_celsius', models.FloatField(default=20.0)),
                ('humidity_threshold_percent', models.FloatField(default=85.0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_facilities', to='cooperatives.cooperative')),
            ],
            options={
                'verbose_name_plural': 'Cold Storage Facilities',
                'ordering': ['cooperative', 'name'],
            },
        ),
    ]
