# Generated by Django 4.2.13 on 2026-06-19 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cooperatives', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coldstoragefacility',
            options={'ordering': ['name'], 'verbose_name_plural': 'Cold Storage Facilities'},
        ),
        migrations.AddField(
            model_name='coldstoragefacility',
            name='gps_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='coldstoragefacility',
            name='gps_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='coldstoragefacility',
            name='is_available_for_rent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coldstoragefacility',
            name='rental_price_per_month',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='RWF per month, shown to cooperatives browsing for space.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='coldstoragefacility',
            name='cooperative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storage_facilities', to='cooperatives.cooperative'),
        ),
        migrations.CreateModel(
            name='WarehouseRentalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_capacity_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('ENDED', 'Ended')], default='PENDING', max_length=20)),
                ('decline_reason', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_rental_requests', to='cooperatives.cooperative')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_requests', to='cooperatives.coldstoragefacility')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'WAREHOUSE_MANAGER'}, on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_manager_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='coldstoragefacility',
            name='warehouse_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facilities', to='cooperatives.warehousemanager'),
        ),
    ]
