# Generated by Django 4.2.13 on 2026-07-12 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0002_alter_coldstoragefacility_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseManagerRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='1-5 stars')),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rated_by_cooperative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cooperatives.cooperative')),
                ('rental_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='cooperatives.warehouserentalrequest')),
                ('warehouse_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='cooperatives.warehousemanager')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
