# Generated by Django 4.2.13 on 2026-07-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0003_warehousemanagerrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouserentalrequest',
            name='requires_iot_monitoring',
            field=models.BooleanField(default=False, help_text='Cooperative needs the rented space to have IoT temperature/humidity monitoring.'),
        ),
    ]
