# Generated by Django 4.2.13 on 2026-07-12 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0004_warehouserentalrequest_requires_iot_monitoring'),
    ]

    operations = [
        migrations.CreateModel(
            name='CooperativeWasteReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_period_start', models.DateField()),
                ('reporting_period_end', models.DateField()),
                ('quantity_dispatched_kg', models.DecimalField(decimal_places=2, help_text='Quantity dispatched to distributors during this period', max_digits=10)),
                ('quantity_discarded_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discard_reason', models.CharField(choices=[('SPOILAGE', 'Spoilage — natural deterioration'), ('NO_DEMAND', 'No demand — not requested by distributors before spoilage'), ('DAMAGE', 'Physical/handling damage in storage'), ('OTHER', 'Other — see notes')], max_length=20)),
                ('discard_notes', models.TextField(blank=True)),
                ('storage_spoilage_loss_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waste_reports', to='cooperatives.cooperative')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
