# Generated by Django 4.2.13 on 2026-06-03 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market_agents', '0001_initial'),
        ('traceability', '0001_initial'),
        ('distribution', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('NATIONAL_KPI_SUMMARY', 'National KPI Summary'), ('DISTRICT_LOSS_REPORT', 'District Loss Report'), ('CROP_LOSS_REPORT', 'Crop Loss Report'), ('COLD_CHAIN_COMPLIANCE', 'Cold Chain Compliance Report'), ('DELIVERY_METHOD_COMPARISON', 'Delivery Method Loss Comparison'), ('STAGE_LOSS_BREAKDOWN', 'Stage-Specific Loss Breakdown'), ('BATCH_TRACEABILITY', 'Per-Batch Traceability Report'), ('MARKET_WASTE', 'Market-Level Waste Report')], max_length=40)),
                ('title', models.CharField(max_length=300)),
                ('format', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel (.xlsx)')], default='PDF', max_length=10)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued for Generation'), ('GENERATING', 'Generating'), ('READY', 'Ready for Download'), ('FAILED', 'Generation Failed')], default='QUEUED', max_length=15)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('filter_district', models.CharField(blank=True, max_length=100)),
                ('generated_by_job', models.BooleanField(default=False)),
                ('file_path', models.FileField(blank=True, upload_to='reports/%Y/%m/')),
                ('file_size_kb', models.IntegerField(blank=True, null=True)),
                ('data_completeness_pct', models.IntegerField(blank=True, help_text='% of expected records received for this period', null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('filter_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='traceability.batch')),
                ('filter_distributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='distribution.distributor')),
                ('filter_market_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='market_agents.marketagent')),
                ('generated_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
